### ISSUE TITLE
Add stream of items

### ISSUE THREAD

**Issue by andre1sk** [sotojuan/exhn#1]
Hey
I wanted to add a function that lets one stream a range of items. Would that be OK?
If yes where would you want that code to go ExHN module or...?

**Comment by sotojuan** [comment]
Hey! Sorry for the late reply. I can work on this before the end of next week, if not today. How do you image the API to be?

**Comment by sotojuan** [comment]
We can do `Stream.map(1..10, &ExHN.item/1)` and get a stream of the results of querying the items with `id` 1 to 100. Is that what you want?

**Comment by sotojuan** [comment]
I've just added an `items` function that takes in a `List` or `Range` of numbers. See [here](https://github.com/sotojuan/exhn/blob/febf77de394a66dda4ab598a1e42dbd289434a27/test/exhn_test.exs#L9) for an example. Let me know if this is good enough to close the issue.

**Comment by andre1sk** [comment]
Sorry was away on vacation, this works thank you for the addition
